# Generated by Django 5.2.1 on 2025-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AstanaHubCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "date_start",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "date_end",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "bin",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
